### ISSUE TITLE
Unexpected values using JC and JC2 for hpo similarity

### ISSUE THREAD

**Issue by aruta321** [anergictcell/pyhpo#20]
Values between JC and JC2 are not similar in pyhpo, but are similar in hpo3. Also, the dataset I am using produces values that range from .1 to 134 in JC and -.1 to -9 in JC2. I've read that the JC score is supposed to be between 0 and 1, so these values wouldn't make sense. Are values outside of 0-1 expected?

I ran the code below using pyhpo versions 3.2.4, 3.2.5, 3.2.6 and hpo3 version 1.0.3.

I made the small example below to demonstrate the differences. 
 ```
from pyhpo import HPOSet, Ontology

 disease_name = "Neurodevelopmental disorder with central hypotonia and dysmorphic facies"
 hpo_terms_to_compare = ['HP:0000218', 'HP:0000384', 'HP:0000842', 'HP:0001212', 'HP:0001274', 'HP:0009796']

  _ = Ontology()
  omim_diseases = list(Ontology.omim_diseases)

 omim_disease_hpo= [list(x.hpo) for x in omim_diseases if disease_name == x.name]
  omim_query = HPOSet.from_queries(omim_disease_hpo[0])
  hpo_query = HPOSet.from_queries(hpo_terms_to_compare)

  jc = hpo_query.similarity(omim_query, kind="omim", method="jc")
  jc2 = hpo_query.similarity(omim_query, kind="omim", method="jc2")

  print(jc)
  print(jc2)
```

This code gives values of 139.57 and -4.31 when using pyhpo v3.2.6 and -4.31 and -4.31 when using hpo3. In addition, there seems to be a discrepancy between versions in pyhpo. Versions 3.2.4 and 3.2.5 both give values of 54.24 and -4.3.

**Comment by anergictcell** [comment]
Hi @aruta321 ,

The `JC` and `JC2` similarity methods gave me a small headache during implementation. The paper was not easy to understand and I also checked the source code of the deprecated `R` package `hposim`. Understanding the logic was not trivial either, but it looked different to the description of the paper:

[Source code](https://github.com/cran/HPOSim/blob/master/R/calcTermSim.r#L15):

```R
      if(term1==term2)
        return(1)  
      else{
        res= - 1/ ( 1 + 2*IC[IC[,1]==an,3] - IC[IC[,1]==term1,3] - IC[IC[,1]==term2,3] )     
        return(res)
      }
```

[Paper of the hposim package](https://doi.org/10.1371/journal.pone.0115692)
<img width="372" alt="image" src="https://github.com/anergictcell/pyhpo/assets/875703/4e2aa173-5f8c-4b8d-bac7-4b16b696a630">

I tried to implement both and named them `jc` and `jc2`. For the [`hpo3`](https://pypi.org/project/hpo3/) package, I only implemented one algorithm and decided to keep both methods, `jc` and `jc2`, but both yielding the same result. I mention this in the [docs](https://hpo3.readthedocs.io/en/stable/hpoterm.html#pyhpo.HPOTerm.similarity_score), but I should have highlighted this more clearly (I will do this in the next update).

The reason for the different results in different pyhpo version is most likely due to usage of different HPO masterdata versions. 

| pyhpo version | HPO Masterdata version|
| --------------| -------------------------|
|  3.2.6 | 2024-03-06  |
| 3.2.5 | 2023-10-09 |
| 3.2.3 | 2023-07-21 |


That all being said, I am not 100% convinced that I implemented the JC algorithm correctly. If you find the results to be wrong and have an idea how to fix this, I would gladly fix the method.

**Comment by aruta321** [comment]
Hi @anergictcell 

I'm not entirely sure why, but the algorithm given in the hposim paper seems to be different than the [original publication](https://arxiv.org/pdf/cmp-lg/9709008.pdf).

![image](https://github.com/anergictcell/pyhpo/assets/164057063/d8e36efb-4e57-4d56-b7d0-2abf731c9eaa)

Here we can see a similar formula is described as the semantic distance between two terms. I believe LSuper(c1, c2) is the same as Tmica based on this [SO question](https://stackoverflow.com/questions/5779197/lowest-superordinate-of-two-concepts-in-a-taxonomy) and this [paper](https://jbiomedsem.biomedcentral.com/articles/10.1186/2041-1480-2-5#:~:text=In%20other%20words%2C%20a%20disjunctive%20ancestor%20is%20the,ancestor%20representing%20a%20given%20set%20of%20parallel%20interpretations.). I don't understand where the subtraction sign comes from. 

To convert the distance to a similarity score we can add one to the distance and take it's inverse. This [package](https://funsimmat.bioinf.mpi-inf.mpg.de/help3.php) and [paper](https://www.sciencedirect.com/science/article/pii/S0169023X06000875) calculate the JC the algorithm below.
![image](https://github.com/anergictcell/pyhpo/assets/164057063/75c8b255-e301-4f04-8633-19cb5565a00c)

This will produce a value between 0 and 1.

**Comment by anergictcell** [comment]
You're absolutely right. That makes way more sense as well. I guess the subtraction sign was a transcription error somewhere. I will fix the calculation accordingly and make an update.
I think it would make sense to deprecate the `jc2` method and only keep `jc` as similarity measurement. There is no need to keep a wrong method.
Thanks a lot for pointing me to the right paper!

**Comment by anergictcell** [comment]
During the implementation I noticed some edge cases: 

Some terms do not have any associated genes or diseases. These terms have an information content of `0`. However, it's likely that those terms have some (grand)parent term with a positive information content. Subsequently, the `IC(MIA)` can be higher than `IC(t)` and the divsor can be less than 1 or even negative, causing negative similarity scores or scores larger than 1.

**Example:**
Similarity between 
- `HP:6000415`: `Intradural spinal lipoma` (Information content: 0.0)
- `HP:0000030` `Testicular gonadoblastoma` (Information content: 0.0)

Common ancestor with highest information content: 
- `HP:0011793` `Neoplasm by anatomical site` (Information content 2.632)

Similarity score:

```text
1 / (0 + 0 - 2 * 2.632 + 1)

1 / -4.264

==> -4.264
```

**Solution:**
If one of the terms (or both) do have an information content of `0`, the method will return a similarity score of `0`. 
This is in line with the purpose of the similarity score, which builds on the concept of information content and linked annotations
